# Generated by Django 3.2.7 on 2021-10-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_alter_job_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='cover_letter',
            field=models.CharField(max_length=500),
        ),
    ]
