# Generated by Django 3.2.7 on 2021-10-05 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0019_auto_20211006_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
